# Generated by Django 6.0.4 on 2026-04-08 20:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تأیید'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درخواست')),
                ('response_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پاسخ')),
                ('note', models.TextField(blank=True, null=True, verbose_name='یادداشت')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_requests', to='books.book', verbose_name='کتاب')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_requests', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'درخواست امانت',
                'verbose_name_plural': 'درخواست\u200cهای امانت',
                'db_table': 'borrow_requests',
            },
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ امانت')),
                ('due_date', models.DateField(verbose_name='تاریخ سررسید')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='تاریخ بازگشت')),
                ('is_returned', models.BooleanField(default=False, verbose_name='بازگردانده شده')),
                ('book_copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrows', to='books.bookcopy', verbose_name='نسخه کتاب')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrows', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('borrow_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrow', to='borrowing.borrowrequest', verbose_name='درخواست مرتبط')),
            ],
            options={
                'verbose_name': 'امانت',
                'verbose_name_plural': 'امانت\u200cها',
                'db_table': 'borrows',
            },
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ جریمه (ریال)')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('borrow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fine', to='borrowing.borrow', verbose_name='امانت')),
            ],
            options={
                'verbose_name': 'جریمه',
                'verbose_name_plural': 'جریمه\u200cها',
                'db_table': 'fines',
            },
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='نام فایل')),
                ('total_rows', models.PositiveIntegerField(verbose_name='تعداد کل ردیف\u200cها')),
                ('success_count', models.PositiveIntegerField(verbose_name='موفق')),
                ('fail_count', models.PositiveIntegerField(verbose_name='ناموفق')),
                ('status', models.CharField(choices=[('success', 'موفق'), ('partial', 'جزئی'), ('failed', 'ناموفق')], max_length=20, verbose_name='وضعیت')),
                ('error_details', models.JSONField(blank=True, null=True, verbose_name='جزئیات خطاها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ورود')),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_logs', to=settings.AUTH_USER_MODEL, verbose_name='وارد کننده')),
            ],
            options={
                'verbose_name': 'لاگ ورود گروهی',
                'verbose_name_plural': 'لاگ\u200cهای ورود گروهی',
                'db_table': 'import_logs',
            },
        ),
    ]
