# Generated by Django 6.0.4 on 2026-04-23 18:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تأیید'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درخواست')),
                ('note', models.TextField(blank=True, null=True, verbose_name='یادداشت')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_requests', to='books.book', verbose_name='کتاب')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_requests', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'درخواست امانت',
                'verbose_name_plural': 'درخواست\u200cهای امانت',
                'db_table': 'borrow_requests',
            },
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ امانت')),
                ('due_date', models.DateField(verbose_name='تاریخ سررسید')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='تاریخ بازگشت')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('returned', 'بازگشت داده شده'), ('overdue', 'تأخیر')], default='active', max_length=20, verbose_name='وضعیت')),
                ('book_copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrows', to='books.bookcopy', verbose_name='نسخه کتاب')),
                ('librarian', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_borrows', to=settings.AUTH_USER_MODEL, verbose_name='کتابدار پردازش\u200cکننده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrows', to=settings.AUTH_USER_MODEL, verbose_name='امانت\u200cگیرنده')),
                ('borrow_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrow', to='borrowing.borrowrequest', verbose_name='درخواست مرتبط')),
            ],
            options={
                'verbose_name': 'امانت',
                'verbose_name_plural': 'امانت\u200cها',
                'db_table': 'borrows',
            },
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ جریمه (ریال)')),
                ('days_late', models.PositiveIntegerField(verbose_name='تعداد روزهای تأخیر')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('borrow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fine', to='borrowing.borrow', verbose_name='امانت')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fines_registered', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
            ],
            options={
                'verbose_name': 'جریمه',
                'verbose_name_plural': 'جریمه\u200cها',
                'db_table': 'fines',
            },
        ),
    ]
