# Generated by Django 6.0.4 on 2026-04-11 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='is_returned',
        ),
        migrations.RemoveField(
            model_name='borrowrequest',
            name='response_date',
        ),
        migrations.RemoveField(
            model_name='fine',
            name='paid_date',
        ),
        migrations.AddField(
            model_name='borrow',
            name='librarian',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_borrows', to=settings.AUTH_USER_MODEL, verbose_name='کتابدار پردازش\u200cکننده'),
        ),
        migrations.AddField(
            model_name='borrow',
            name='status',
            field=models.CharField(choices=[('active', 'فعال'), ('returned', 'بازگشت داده شده'), ('overdue', 'تأخیر')], default='active', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='fine',
            name='days_late',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد روزهای تأخیر'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fine',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت'),
        ),
        migrations.AddField(
            model_name='fine',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fines_registered', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrows', to=settings.AUTH_USER_MODEL, verbose_name='امانت\u200cگیرنده'),
        ),
        migrations.DeleteModel(
            name='ImportLog',
        ),
    ]
