# Generated by Django 6.0.4 on 2026-04-08 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('author', models.CharField(max_length=255, verbose_name='نویسنده')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='شابک')),
                ('publisher', models.CharField(blank=True, max_length=255, null=True, verbose_name='ناشر')),
                ('publish_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='سال انتشار')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='دسته\u200cبندی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='تصویر جلد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'کتاب',
                'verbose_name_plural': 'کتاب\u200cها',
                'db_table': 'books',
            },
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True, verbose_name='موجود')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='books.book', verbose_name='کتاب')),
            ],
            options={
                'verbose_name': 'نسخه کتاب',
                'verbose_name_plural': 'نسخه\u200cهای کتاب',
                'db_table': 'book_copies',
            },
        ),
    ]
