# Generated by Django 6.0.4 on 2026-04-12 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='نام فایل')),
                ('total_rows', models.IntegerField(verbose_name='کل ردیف\u200cها')),
                ('success_count', models.IntegerField(verbose_name='موفق')),
                ('fail_count', models.IntegerField(verbose_name='ناموفق')),
                ('errors', models.TextField(blank=True, verbose_name='خطاها')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان import')),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_logs', to=settings.AUTH_USER_MODEL, verbose_name='وارد کننده')),
            ],
            options={
                'verbose_name': 'لاگ import',
                'verbose_name_plural': 'لاگ\u200cهای import',
                'db_table': 'import_logs',
            },
        ),
    ]
